FROM grammatech/ddisasm AS ddisasm 

FROM gcr.io/fuzzbench/base-image

ENV DEBIAN_FRONTEND=noninteractive 
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/out"
ENV PATH="$PATH:/out"

ENV AFL_SKIP_CPUFREQ=1
ENV AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
ENV AFL_TESTCACHE_SIZE=2
